services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    # build: .    
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - cosmosdb
    
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
    - "8081:8081"
    volumes:
      - cosmosdb-data:/var/opt/data

volumes:
  cosmosdb-data:
